### ISSUE TITLE
rga_copy_with_rotate

### ISSUE THREAD

**Issue by wzyy2** [yakir-Yang/libdrm-rockchip#1]
It seems incorrect here.

```
	if (degree != 0 || degree != 90 || degree != 180 || degree != 270) {
		fprintf(stderr, "invalid rotate degree %d.\n", degree);
		return -EINVAL;
	}
```

**Comment by yakir-Yang** [comment]
Yeah, it's wrong, thanks for pointing out.

    if (degree != 0 && degree != 90 && degree != 180 && degree != 270) {
        fprintf(stderr, "invalid rotate degree %d.\n", degree);
        return -EINVAL;
    }
