### ISSUE TITLE
rga_copy 

### ISSUE THREAD

**Issue by wzyy2** [yakir-Yang/libdrm-rockchip#2]
rga_copy那里长宽的判断还是有点问题
我直接改成这样了
```
int rga_copy(struct rga_context *ctx, struct rga_image *src,
             struct rga_image *dst, unsigned int src_x, unsigned int src_y,
             unsigned int dst_x, unsigned dst_y, unsigned int w,
             unsigned int h)
{
        return rga_multiple_transform(ctx, src, dst, src_x, src_y, w,
                                      h, dst_x, dst_y, w, h,
                                      0, 0, 0);
}
```

**Comment by yakir-Yang** [comment]
COPY API 的 w/h 判断是有问题，但是我不认为要删除。如果没有一定的条件判断，假如 Src / Dst 的 (x + w, y + h) 超过 Buffer Size 的话，则会直接出现 RGA 硬件模块写到其他内存，非常不安全。（个人建议最好不要直接使用 multiple API，除非你能保证输入参数的正确性）。

我觉得长宽判断改成如下条件即可满足要求：

int rga_copy(struct rga_context *ctx, struct rga_image *src,
             struct rga_image *dst, unsigned int src_x, unsigned int src_y,
             unsigned int dst_x, unsigned dst_y, unsigned int w,
             unsigned int h)
{
        unsigned int src_w = 0, src_h = 0, dst_w = 0, dst_h = 0;             
                                                                             
        src_w = w;                                                           
        src_h = h;                                                           
        if (src_x + src_w > src->width)                                          
                src_w = src->width - src_x;                                  
        if (src_y + src_h > src->height)                                         
                src_h = src->height - src_y;                          
                                                                             
        dst_w = w;                                                           
        dst_h = h;                                                           
        if (dst_x + dst_w > dst->width)                                          
                dst_w = dst->width - dst_x;                                  
        if (dst_y + dst_h > dst->height)                                         
                dst_h = dst->height - dst_y;                                 
                                                                             
        w = (src_w < dst_w) ? src_w : dst_w;                                 
        h = (src_h < dst_h) ? src_h : dst_h;                                 
                                                                             
        if (w <= 0 || h <= 0) {                                              
                fprintf(stderr, "invalid width or height.\n");               
                rga_reset(ctx);                                              
                return -EINVAL;                                              
        }       
                                                             
        return rga_multiple_transform(ctx, src, dst, src_x, src_y, w,
                                      h, dst_x, dst_y, w, h,
                                      0, 0, 0);
}
