### ISSUE TITLE
RK3188可以使用吗？

### ISSUE THREAD

**Issue by fjyihan** [yakir-Yang/libdrm-rockchip#3]
想在RK3188上跑Linux系统，现在2D显示效率不高，想用drm优化显示。
RK3188 Android 4.4 SDK的内核驱动似乎没有DRM RGA的部分代码。
如果想在RK3188 Android 4.4 BOX kernel的基础上使用到DRM，要怎么修改？
谢谢。

**Comment by yakir-Yang** [comment]
RK3188 SDK 目前不支持 DRM 接口，没法用这个 RGA 驱动来加速。Android 上如果要添加 DRM 的支持，需要重写 Kernel + HWC + SurfaceFlinger 层代码，非常复杂。
